#!/usr/bin/env python3
"""Local development onboarding for the pickled-spec monorepo.

Writes ``pickled.config.yaml``, merges a ``pickled-spec`` MCP server entry into
Cursor config, and optionally runs the stdio smoke test. Stdlib only.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

ActionKind = Literal[
    "CREATE",
    "UPDATE",
    "REPLACE",
    "SKIP",
    "BACKUP",
    "INSERT",
    "ABORT",
]


@dataclass(frozen=True, slots=True)
class PlanRow:
    """One planned or completed filesystem action."""

    path: str
    action: ActionKind
    detail: str = ""


def log(level: str, message: str) -> None:
    """Write a timestamped line to stderr."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    sys.stderr.write(f"{ts} [{level}] {message}\n")


def resolve_repo_root() -> Path:
    """Return monorepo root (parent of ``scripts/``)."""
    root = Path(__file__).resolve().parent.parent
    if not (root / "pyproject.toml").is_file():
        log("ERROR", f"pyproject.toml not found under {root}")
        sys.exit(2)
    return root


def require_uv() -> None:
    """Abort if ``uv`` is not on PATH."""
    if shutil.which("uv") is None:
        log(
            "ERROR",
            "uv not found on PATH. Install: curl -LsSf https://astral.sh/uv/install.sh | sh",
        )
        sys.exit(2)


def cursor_config_path(kind: str) -> Path | None:
    """Resolve Cursor MCP JSON path for ``global``, ``project``, or ``none``."""
    if kind == "none":
        return None
    if kind == "project":
        return resolve_repo_root() / ".cursor" / "mcp.json"
    home = Path(os.environ.get("USERPROFILE", Path.home()))
    if os.name == "nt":
        return home / ".cursor" / "mcp.json"
    return Path.home() / ".cursor" / "mcp.json"


def config_yaml_body(provider: str, model: str, api_key_env: str) -> str:
    """Emit fixed-shape ``pickled.config.yaml`` without a YAML library."""
    return (
        "# Auto-generated by scripts/setup_local_dev.py.\n"
        "# Re-run with --force to regenerate.\n"
        "providers:\n"
        f"  {provider}:\n"
        f"    type: {provider}\n"
        f"    default_model: {model}\n"
        f"    api_key_env: {api_key_env}\n"
    )


def mcp_server_entry(repo_root: Path) -> dict[str, Any]:
    """Build the ``pickled-spec`` MCP server object for Cursor."""
    return {
        "command": "uv",
        "args": [
            "run",
            "--directory",
            str(repo_root.resolve()),
            "--extra",
            "mcp",
            "pickled-spec",
            "mcp",
            "--transport",
            "stdio",
        ],
    }


def backup_path(target: Path) -> Path:
    """Return a UTC-stamped backup path next to ``target``."""
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    return target.with_name(f"{target.name}.bak.{stamp}")


def write_pickled_config(
    repo_root: Path,
    *,
    provider: str,
    model: str,
    api_key_env: str,
    force: bool,
    dry_run: bool,
    rows: list[PlanRow],
) -> None:
    """Create or skip ``pickled.config.yaml`` at the repo root."""
    path = repo_root / "pickled.config.yaml"
    rel = str(path)
    body = config_yaml_body(provider, model, api_key_env)
    if path.is_file() and path.read_text(encoding="utf-8").strip() and not force:
        log("INFO", f"SKIP {rel} (already exists)")
        rows.append(PlanRow(rel, "SKIP", "config exists"))
        return
    action: ActionKind = "REPLACE" if path.is_file() and force else "CREATE"
    if dry_run:
        log("INFO", f"DRY-RUN would {action} {rel}")
        rows.append(PlanRow(rel, action))
        return
    path.write_text(body, encoding="utf-8")
    log("INFO", f"{action} {rel}")
    rows.append(PlanRow(rel, action))


def _load_mcp_json(path: Path) -> dict[str, Any]:
    """Parse Cursor MCP config; abort on malformed JSON."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        log("ERROR", f"malformed JSON in {path}: {exc}")
        sys.exit(2)
    if not isinstance(data, dict):
        log("ERROR", f"expected JSON object at root of {path}")
        sys.exit(2)
    return data


def _diff_entry(existing: dict[str, Any], desired: dict[str, Any]) -> str:
    """Unified diff between two MCP server entries."""
    old_lines = json.dumps(existing, indent=2, sort_keys=True).splitlines(keepends=True)
    new_lines = json.dumps(desired, indent=2, sort_keys=True).splitlines(keepends=True)
    return "".join(
        difflib.unified_diff(old_lines, new_lines, fromfile="existing", tofile="desired")
    )


def merge_cursor_mcp(
    config_path: Path,
    *,
    server_name: str,
    entry: dict[str, Any],
    force: bool,
    dry_run: bool,
    rows: list[PlanRow],
) -> None:
    """Insert or update one MCP server entry; preserve other servers."""
    rel = str(config_path)
    desired_root: dict[str, Any] = {"mcpServers": {server_name: entry}}

    if not config_path.is_file():
        if dry_run:
            log("INFO", f"DRY-RUN would CREATE {rel}")
            rows.append(PlanRow(rel, "CREATE"))
            return
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(
            json.dumps(desired_root, indent=2, sort_keys=False) + "\n",
            encoding="utf-8",
        )
        log("INFO", f"CREATE {rel}")
        rows.append(PlanRow(rel, "CREATE"))
        return

    data = _load_mcp_json(config_path)
    servers = data.get("mcpServers")
    if servers is None:
        servers = {}
        data["mcpServers"] = servers
    if not isinstance(servers, dict):
        log("ERROR", f"mcpServers must be an object in {rel}")
        sys.exit(2)

    current = servers.get(server_name)
    if current is None:
        action: ActionKind = "INSERT"
        servers[server_name] = entry
    elif current == entry:
        log("INFO", f"SKIP {rel} entry {server_name!r} (unchanged)")
        rows.append(PlanRow(rel, "SKIP", server_name))
        return
    elif not force:
        log("ERROR", f"conflict for mcpServers[{server_name!r}] in {rel} (use --force)")
        sys.stderr.write(_diff_entry(current, entry))
        rows.append(PlanRow(rel, "ABORT", server_name))
        sys.exit(2)
    else:
        action = "REPLACE"
        servers[server_name] = entry

    out_text = json.dumps(data, indent=2, sort_keys=False) + "\n"
    if dry_run:
        log("INFO", f"DRY-RUN would {action} {rel} ({server_name})")
        rows.append(PlanRow(rel, action, server_name))
        return

    bak = backup_path(config_path)
    shutil.copy2(config_path, bak)
    log("INFO", f"BACKUP {bak}")
    rows.append(PlanRow(str(bak), "BACKUP"))

    config_path.write_text(out_text, encoding="utf-8")
    log("INFO", f"{action} {rel} entry {server_name!r}")
    rows.append(PlanRow(rel, action, server_name))


def run_smoke(repo_root: Path, dry_run: bool, rows: list[PlanRow]) -> int:
    """Run ``scripts/smoke_mcp_stdio.py`` via uv."""
    script = repo_root / "scripts" / "smoke_mcp_stdio.py"
    rel = str(script)
    if dry_run:
        log("INFO", f"DRY-RUN would run smoke test: {rel}")
        rows.append(PlanRow(rel, "SKIP", "dry-run"))
        return 0
    log("INFO", f"running smoke test: {rel}")
    completed = subprocess.run(
        ["uv", "run", "python", str(script)],
        cwd=str(repo_root),
        check=False,
    )
    code = int(completed.returncode)
    smoke_action: ActionKind = "SKIP" if code == 0 else "ABORT"
    rows.append(PlanRow(rel, smoke_action, f"exit {code}"))
    if code != 0:
        log("WARN", f"smoke test exited {code}")
    else:
        log("INFO", "smoke test passed")
    return code


def print_summary(rows: list[PlanRow]) -> None:
    """Print a two-column action table to stderr."""
    if not rows:
        return
    width = max(len(r.path) for r in rows)
    sys.stderr.write(f"\n{'path'.ljust(width)} | action\n")
    sys.stderr.write(f"{'-' * width}-|--------\n")
    for row in rows:
        detail = f" ({row.detail})" if row.detail else ""
        sys.stderr.write(f"{row.path.ljust(width)} | {row.action}{detail}\n")


def print_next_steps(api_key_env: str) -> None:
    """Print post-setup instructions to stderr."""
    sys.stderr.write(
        "\nNext steps:\n"
        f"- Set {api_key_env} in your shell rc if not already set.\n"
        "- Restart Cursor (fully quit, reopen).\n"
        "- In a fresh Cursor chat, ask: 'List available MCP tools.' — expect at "
        "least a dozen prefixed bdd_/rules_/schema_/iac_/data_/diff_.\n"
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Build CLI argument parser."""
    parser = argparse.ArgumentParser(
        description="Onboard local dev: pickled.config.yaml, Cursor MCP, optional smoke.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions; write nothing.",
    )
    parser.add_argument(
        "--cursor-config",
        choices=("global", "project", "none"),
        default="global",
        help="Where to merge the pickled-spec MCP entry.",
    )
    parser.add_argument(
        "--server-name",
        default="pickled-spec",
        help="mcpServers key in Cursor config.",
    )
    parser.add_argument("--provider", default="anthropic", help="LLM provider id.")
    parser.add_argument(
        "--default-model",
        default="claude-sonnet-4-5-20250929",
        help="default_model in pickled.config.yaml.",
    )
    parser.add_argument(
        "--api-key-env",
        default="ANTHROPIC_API_KEY",
        help="Environment variable name for the API key.",
    )
    parser.add_argument("--skip-config", action="store_true", help="Skip pickled.config.yaml.")
    parser.add_argument("--skip-smoke", action="store_true", help="Skip smoke_mcp_stdio.py.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing config and replace conflicting MCP entries.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run onboarding steps; return process exit code."""
    args = parse_args(argv)
    rows: list[PlanRow] = []
    warn = False

    repo_root = resolve_repo_root()
    require_uv()

    if not os.environ.get(args.api_key_env):
        log("WARN", f"{args.api_key_env} is not set in the environment")
        warn = True

    if not args.skip_config:
        write_pickled_config(
            repo_root,
            provider=args.provider,
            model=args.default_model,
            api_key_env=args.api_key_env,
            force=args.force,
            dry_run=args.dry_run,
            rows=rows,
        )

    mcp_path = cursor_config_path(args.cursor_config)
    if mcp_path is not None:
        merge_cursor_mcp(
            mcp_path,
            server_name=args.server_name,
            entry=mcp_server_entry(repo_root),
            force=args.force,
            dry_run=args.dry_run,
            rows=rows,
        )

    smoke_code = 0
    if not args.skip_smoke and not args.dry_run:
        smoke_code = run_smoke(repo_root, args.dry_run, rows)
        if smoke_code != 0:
            warn = True

    print_summary(rows)
    print_next_steps(args.api_key_env)

    if args.dry_run:
        plan = [{"path": r.path, "action": r.action, "detail": r.detail} for r in rows]
        sys.stdout.write(json.dumps({"plan": plan}) + "\n")
        return 1 if warn else 0

    return 1 if warn else 0


if __name__ == "__main__":
    sys.exit(main())
